### ISSUE TITLE
only can you help to find data to run your code 

### ISSUE THREAD

**Issue by Sandy4321** [ts302team/KDDCUP2019-AutoMLTrack#1]
great code thanks
only can you help to find data to run your code 
KDD Cup 2019 AutoML for Temporal Relational Data
https://codalab.lri.fr/competitions/559

**Comment by zypangpang** [comment]
The data is in our lab PCs. Since COVID-19, we are stuck at home and cannot reach that data. If you really need it, we can upload it to a netdisk and share to you when we return to the college.

**Comment by Sandy4321** [comment]
Great thanks. Please share data asap

**Comment by zypangpang** [comment]
Data https://cloud.tsinghua.edu.cn/f/87b3f36489b04194914d
Just ignore the codes inside.

**Comment by Sandy4321** [comment]
great, can you also share link to details to understand this data, yours or somebody else material ?
only in English pls
